web:
  restart: always
  build: ./web/
  command: script/fixmystreet_app_server.pl -d --fork
  links:
    - db:db
  expose:
    - 3000

db:
  restart: always
  image: dalekurt/postgres:9.3
  volumes_from:
    - data
  ports:
    - "5432:5432"

data:
  restart: always
  image: dalekurt/postgres:9.3
  volumes:
    - /tmp/data:/var/lib/postgresql/data

frontend:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  links:
    - web:web
