app:
  restart: always
#  build: ./app/
  image: fms:test
  command: /fms/script/fixmystreet_app_server.pl -d --fork
  links:
    - db:db
  expose:
    - 3000
  volumes:
    - /fms
  command: bash -c "/fms/script/fixmystreet_app_server.pl -d --fork"

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80"
  links:
    - app:app
  volumes_from:
    - app

db:
  restart: always
  image: dalekurt/postgres:9.4
  ports:
    - "5432:5432"
  env_file: db.env
