web:
  restart: always
  build: ./web/
  command: script/fixmystreet_app_server.pl -d --fork
  links:
    - db:db
  expose:
    - 3000
  volumes:
    - /fms
  command: bash -c "/fms/script/fixmystreet_app_server.pl -d --fork"

frontend:
  restart: always
  build: ./nginx/
  ports:
    - "80"
  links:
    - web:web
  volumes-from:
    - web

db:
  restart: always
  image: dalekurt/postgres:9.4
  ports:
    - "5432:5432"

